### PR TITLE
Code review: milestone 2

### PR DESCRIPTION
**Pull request by bafiam**
#### What does this PR do?
1. Set up the project directory.
2. display/print out a message using bash command `ruby bin/main.rb`
3. The project consist of a user interface only **without the game logic**
#### How should this be manually tested?
Clone the repo then navigate to the project directory, on the terminal type `bin/main.rb`

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team !  

### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.


*  [REQUIRED] game should inform player if selected move is invalid
*  [REQUIRED] game should inform player if selected move is a winning move
*  [REQUIRED] game should inform player if selected move is a draw move


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by Anna-Myzukina** [comment]
Kindly recommended test your game, now it gives new errors

* When user choose  move your game shows message: "That position has already been taken"
tictactoe

##### Implementation details

*  A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* Inside loop, student should all actions repeated for each move
* A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Forison — APPROVED** [review]
## Status: Approved💚
## Hi Team🙌
Good job so far, Let us take note of the remarks below👇
- For now, your game does not inform the player if the selected move is invalid, it is a requirement in this milestone, and the next one as well. I will give you a pass in this one since you have not started implementing the main logic. the player should not be able to select an already occupied spot.
- There is a bug you also have to address. What happens if the player does not select a value from one to nine? Now the game throw an error . "no implicit conversion from nil to integer (TypeError)" when that occurs. Let us address it. To make the project more robust.
#### That is it. Take good note of these suggestions, proceed to milestone 3
#### Happy coding💻
#### Addo Forison

**Pull request merged**
